name: firebase_32
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # BLoC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Navigation
  go_router: ^14.0.0

  # Utils
  equatable: ^2.0.5
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
